import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "../components/root/sidebar-menu/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-row min-h-screen bg-gray-100">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
